apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecct3-deployment

spec: 
  replicas: 3

  selectors:
    matchLabels:
      app: project3


    template:
      metadata:
        labels:
          app: project3


      spec:
        containers:
          - name: project3-container
            image: parthh21/project3:latest

            ports:
              - containerPort: 5000



---
apiVersion: v1
kind: Service
metadata:
  name: project3-service

spec: 
  type: LoadBalancer

  selector:
    app: project3

  ports:
    - port: 80
      targetPorts: 5000
